export const BLOG_POSTS = [
  {
    id: 1,
    slug: "the-roi-of-relaxation-why-chair-massage-works",
    category: "Corporate Culture",
    readTime: "5 min read",
    title: "The ROI of Relaxation: Why Chair Massage Works",
    description: "Discover how integrating short massage sessions can significantly boost employee productivity and reduce medical leaves.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDhB-IX1D737i4KTvOeM4XBpkVnT9Cs9TCInF-j6QHlHwvIlbnoqDq-UMf5kZEm7th3f2Vw-eQuFdK9KPvLSx_XgVvlT2K0-BZoAXLAeWsxbPdln1TFA6Boz1BC64DcPIOMzRhvGx0wfQdN8Wkwgy3SowyL8YRmSUBPkOfI9R-5BvFM2rKzqa2KXlw0TyqZ2iNmt_UpKAlZxjCq1QBvTVHM3P05nckM9ymtFZsNQp2ORVWJWyVSxpqbfvXN8PuEHglPqUzUWsuAMiM",
    date: "March 24, 2026",
    author: "Dr. Sarah Mitchell",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h3 class=\"text-2xl font-bold mt-8 mb-4\">The Core Benefits</h3><p>Duis aute irure dolor in reprehenderit in voluptate velit esse.</p>",
  },
  {
    id: 2,
    slug: "ergonomic-mistakes-your-team-is-making-right-now",
    category: "Ergonomics",
    readTime: "8 min read",
    title: "Ergonomic Mistakes Your Team is Making Right Now",
    description: "A deep dive into common office posture pitfalls and simple fixes that prevent long-term musculoskeletal issues.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA26INpncmdvWbvRUV9yM65_PFfcd9kDQlm5ZsI4jnnCuWxRxug6VXqCGAp0ZGnWt3-Pc2QDbLT-mwibLdcrDhV3npRbPatP4y7W6QPloI0AzwPwklMgfCbIRaeBw1a-HDL3hY7GoCV9I5b1PS-JzAlt0wHww2K-ZMXsD0xQ1ewqb1SZDtCZo_g-sxBvvnXsoBqwfrX65-65atmblMnL3AvbfLtjoca4fvFJ9mcShS1j9yis1GXyb3iue7R2QxCmY2ei14oc13nYsY",
    date: "March 20, 2026",
    author: "Mark Henderson",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h3 class=\"text-2xl font-bold mt-8 mb-4\">The Core Benefits</h3><p>Duis aute irure dolor in reprehenderit in voluptate velit esse.</p>",
  },
  {
    id: 3,
    slug: "combating-burnout-with-15-minute-interventions",
    category: "Mental Health",
    readTime: "4 min read",
    title: "Combating Burnout with 15-Minute Interventions",
    description: "Practical strategies for HR leaders to implement micro-breaks that actually refresh the mind and body.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCeNC58_aqE9xMo0oJ3KcaZZ6frRQT0DtzHNUEVzcRrRxDd7N1pLk9pcV66sIMzNlgRrpqU5J135zgJxGWRRagQ4hzPh8IJoyKgGeYPNcAqBF7yBN6oRsoWFum6iPxSQAh0YcbMXuBL4QlT9OataYDgGKP_Xf2YxWJbxf47p3Y7ZgmjohQX0nGEHV7SMTx_ozP-qiqGtmBpIKMn6lVb2x8nLSBlrcZQ-WJnCPJYT78-GBeYJSfEVbZmLrYtf_L-wv_6xcJNxXT2dHg",
    date: "March 15, 2026",
    author: "Emma Larson",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h3 class=\"text-2xl font-bold mt-8 mb-4\">The Core Benefits</h3><p>Duis aute irure dolor in reprehenderit in voluptate velit esse.</p>",
  },
  {
    id: 4,
    slug: "building-a-wellness-first-workplace-in-2026",
    category: "Leadership",
    readTime: "6 min read",
    title: "Building a Wellness-First Workplace in 2026",
    description: "What modern candidates are looking for in company benefits and how to stand out in the talent war.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDsDM0tJU_ZE8rz7uZEiVw7YSkok3yLJ0XSTsmzdCIkyy5a9QOgopRGC_G4LG9QbHc-zPVJil_W2P4qS2tsnDNMUKy1CNcc36qN02W7zPL7zbbbDF-CTGB1e22zzn1hTaGqLqIqD_h89RqLCnKOXIENo1PRqsFdzYHfAgDgkHZjZbmRzw1QMFXAxEQwKeAOBkBF_33I-HLhnB9Wv901Nrn-dThvrSW461RH4SDmWu3T2ndhokB8p4RP1D_5QNgOe86T73PGNKIS3AM",
    date: "March 10, 2026",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h3 class=\"text-2xl font-bold mt-8 mb-4\">The Core Benefits</h3><p>Duis aute irure dolor in reprehenderit in voluptate velit esse.</p>",
    author: "James Wilson"
  },
  {
    id: 5,
    slug: "the-science-of-touch-stress-reduction-mechanics",
    category: "Science",
    readTime: "7 min read",
    title: "The Science of Touch: Stress Reduction Mechanics",
    description: "Understanding the physiological response to chair massage, from cortisol reduction to improved circulation.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDhWLmqVjfyupNxZHGum_fZT5xj6A9TL8TDLuR3v31s6C-Fn8MQgkZwGg5BYKqqMH-nFuLGrt9kPfSe8ju1DxZIXhTn8JYWSV4e44zm2pTMn8pc5rcJTdPOXrwttjr9Bw4fwuh8w8NjGN6X9LRMojRwmSC12tIc7ydC0djBfSPZEUfaW_jcCTsGClcY1eATAjPe6WeaIz8JfuGwTn-l3Giw5JO_ACOon_yOEO05yXOkHvYofJp0oP4oz4bUaMm7iSaFpyczlmf-_I0",
    date: "March 5, 2026",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h3 class=\"text-2xl font-bold mt-8 mb-4\">The Core Benefits</h3><p>Duis aute irure dolor in reprehenderit in voluptate velit esse.</p>",
    author: "Dr. Elena Rostova"
  },
  {
    id: 6,
    slug: "budgeting-for-wellness-a-guide-for-hr-professionals",
    category: "HR Strategy",
    readTime: "5 min read",
    title: "Budgeting for Wellness: A Guide for HR Professionals",
    description: "How to present a wellness initiative proposal that gets approved by CFOs and senior leadership.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDSSBC03BKnzQkht87wcJ8FCPhW1UChMl94QwG4BPEOKFpRNTTCJL3DJXGSRNUilmlJK02FUwxUiuLq9KN1K63o2P59id4GcMS6Vjt7KyOAh1I-OyjUdUnS2VF8EnBUDyBFbdJJj32nG9QAz2YRiSArMlJIyoc040fCUR4Aw6Fe-eTEz8ZH5B2P-AGBrC65O48WA1nubmIBe0IY7mk6hmtiqzp1KvUxCahRH54X_jIZn--s3DSRgdj5U3H68hCGGCRVUnCEsQDV4I0",
    content: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><h3 class=\"text-2xl font-bold mt-8 mb-4\">The Core Benefits</h3><p>Duis aute irure dolor in reprehenderit in voluptate velit esse.</p>",
    date: "March 1, 2026",
    author: "Michael Chang"
  },
];
